version: '3.7'

services:
  apiprod:
    image: tecnofit:latest
    ports:
      - "8181:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: api
      DB_PASS: 123456
      DB_NAME: tecnofit
  api:
    build:
      dockerfile: docker/dev/Dockerfile
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      MODE: DEV
      DB_HOST: db
      DB_USER: api
      DB_PASS: 123456
      DB_NAME: tecnofit

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tecnofit
      MYSQL_USER: api
      MYSQL_PASSWORD: 123456
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  dbtest:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tecnofit
      MYSQL_USER: api
      MYSQL_PASSWORD: 123456
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
